stages:
  - build
  - deploy

cache:
  paths:
    - node_modules
    - dist

build:
  image: node:8.11.1
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  image: node:8.11.1
  stage: deploy
  script:
    - npm run deploy
  only:
    - master
  allow_failure: false
  when: manual
  environment:
    name: production
    url: {{ builds_url }}{{ build_id }}-{{ name }}
